#!/bin/sh
export PATH="/bin:/sbin:/usr/sbin:/usr/bin"

OLDGW=`netstat -nr | grep 'ppp0' | grep 'UH ' | sed 's/ \([0-9.]*\).*/\1/g'`

if [ ! -e /tmp/pptp_oldgw ]; then
    echo "${OLDGW}" > /tmp/pptp_oldgw
fi

dscacheutil -flushcache
route add 106.75.0.0/16 "${OLDGW}" # gitlab
route add 123.59.0.0/16 "${OLDGW}" # yapi
